### ISSUE TITLE
How to change the used objects given by the innerHTML code?

### ISSUE THREAD

**Issue by dirsigler** [Jaredk3nt/homepage#1]
Hey buddy,

thanks for this beautiful homepage.
I am trying to change the openweather API to the darksky one.

Somehow I am not able to change the strings which are given to the innerHTML stuff from the JSON output.

The output of the JSON is:

{
  "latitude": 51.11919,
  "longitude": 6.951266,
  "timezone": "Europe/Berlin",
  "currently": {
    "time": 1549020317,
    "summary": "Mostly Cloudy",
    "icon": "partly-cloudy-day",
    "precipIntensity": 0,
    "precipProbability": 0,
    "temperature": 3.62,
    "apparentTemperature": 0.06,
    "dewPoint": 1.04,
    "humidity": 0.83,
    "pressure": 990.58,
    "windSpeed": 4.18,
    "windGust": 6.4,
    "windBearing": 146,
    "cloudCover": 0.78,
    "uvIndex": 1,
    "visibility": 11.1,
    "ozone": 354.99
  },
  "offset": 1
}

what I do now is:

document.getElementById("temp").innerHTML = json.currently.temperature;//.toFixed(0) + " C";

But somehow it is blank on the homepage.
Can you give me please a hint where I have to look?

**Comment by Jaredk3nt** [comment]
Could you post a gist of your index.html so I can run it? It looks fine to me from what you have explained.

**Comment by d7eeem** [comment]
Thank YOU very so much, this HomePage is amazing but i am having the same problem! :(
