### ISSUE TITLE
Start searching as you type (feature request)

### ISSUE THREAD

**Issue by DarkSiderOC** [Jaredk3nt/homepage#3]
Now you need to press the space bar to trigger the search, as you rapidly open a tab pressing the space bar breaks you rapidity.

If you like it I can submit a PR about this.
Nice project by the way!

**Comment by DarkSiderOC** [comment]
Also, opening the search results in another page is annoying, if you search 2 things you'll end up with 8 tabs

**Comment by Jaredk3nt** [comment]
Howdy, thanks for your interest in the project ❤️!

Both only searching on space and opening in a new window are intentional for this project. Please feel free to fork the project and add those features for your own use, however I would like to keep those things as-is for this repo.
