### ISSUE TITLE
Server returns: 404 NOT_FOUND

### ISSUE THREAD

**Issue by hexandcube** [Jaredk3nt/homepage#4]
https://danggoodcode.com/startpage returns HTTP 404 on Zeit Now
![image](https://user-images.githubusercontent.com/41151156/68499750-423fa180-025a-11ea-8668-597002013a3e.png)

**Comment by Jaredk3nt** [comment]
Sorry the site was taken down quite a while ago, I can work on setting up another instance of it sometime soon
