### ISSUE TITLE
Default scrollbars on Firefox 70.0

### ISSUE THREAD

**Issue by hexandcube** [Jaredk3nt/homepage#5]
![image](https://user-images.githubusercontent.com/41151156/68529804-b03fa380-0302-11ea-878b-3408e1c1c135.png)

**Comment by Jaredk3nt** [comment]
This has been a known issue on windows machines for awhile, I am open to PRs to add custom styling to replace them if anyone wants to take a look.

**Comment by Jaredk3nt** [comment]
@hexandcube I went ahead and took a crack at it. I am only on a mac so I'm not 100% sure this will solve it so let me know. We can reopen this if it is not solved.

(forgot to link commit to this issue but the most recent changes include the scrollbar styling)
